@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PlannerParser" as PlannerParser LOGIC_COLOR
participant ":AddProjectCommandParser" as AddProjectCommandParser LOGIC_COLOR
participant "d:AddProjectCommand" as AddProjectCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add project Duke")
activate LogicManager

LogicManager -> PlannerParser : parseCommand("add project Duke")
activate PlannerParser

create AddProjectCommandParser
PlannerParser -> AddProjectCommandParser
activate AddProjectCommandParser

AddProjectCommandParser --> PlannerParser
deactivate AddProjectCommandParser

PlannerParser -> AddProjectCommandParser : parse("Duke")
activate AddProjectCommandParser

create AddProjectCommand
AddProjectCommandParser -> AddProjectCommand
activate AddProjectCommand

AddProjectCommand --> AddProjectCommandParser :
deactivate AddProjectCommand

AddProjectCommandParser --> PlannerParser : d
deactivate AddProjectCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddProjectCommandParser -[hidden]-> PlannerParser
destroy AddProjectCommandParser

PlannerParser --> LogicManager : d
deactivate PlannerParser

LogicManager -> AddProjectCommand : execute(m)
activate AddProjectCommand

AddProjectCommand -> Model : addProject(Duke)
activate Model

Model --> AddProjectCommand
deactivate Model

create CommandResult
AddProjectCommand -> CommandResult
activate CommandResult

CommandResult --> AddProjectCommand
deactivate CommandResult

AddProjectCommand --> LogicManager : r
deactivate AddProjectCommand

[<--LogicManager
deactivate LogicManager
@enduml
