@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Planner *-right-> "1" ProjectList

ProjectList -right-> Project

Project *--> Name
Project *--> Comment
Project *--> Member
Member *--> Name
Task *--> Name
Task *--> Member
Project *--> Task

@enduml
