@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "Planner Storage" #F4F6F6{
Class "<<interface>>\nPlannerStorage" as PlannerStorage
Class JsonPlannerStorage
Class JsonSerializablePlanner
Class JsonAdaptedProject
Class JsonAdaptedTask
Class JsonAdaptedComment
Class JsonAdaptedMember
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" PlannerStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> PlannerStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonPlannerStorage .up.|> PlannerStorage
JsonPlannerStorage ..> JsonSerializablePlanner
JsonSerializablePlanner --> "*" JsonAdaptedProject
JsonAdaptedProject --> "*" JsonAdaptedTask
JsonAdaptedProject --> "*" JsonAdaptedComment
JsonAdaptedProject --> "*" JsonAdaptedMember

@enduml
